config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :clients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :client
end

app/models/client.rb
class Client < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:appType, :appClient, :appDate, :appTime, :appLength, :client_id)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :'Training Type' %>
    <%= form.text_field :appType %>
  </div>

  <div class="field">
    <%= form.label :'Pet Name' %>
    <%= form.text_field :appClient %>
  </div>

  <div class="field">
    <%= form.label :'Date of Appointment' %>
    <%= form.date_select :appDate %>
  </div>

  <div class="field">
    <%= form.label :'Time of Appointment' %>
    <%= form.time_select :appTime %>
  </div>

  <div class="field">
    <%= form.label :'Appointment Length' %>
    <%= form.number_field :appLength %>
  </div>

  <div class="field">
    <%= form.label :'Client' %>
    <%= form.text_field :client_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<button><%= link_to 'New Appointment', new_appointment_path %></button>
<button><%= link_to 'New Client', new_client_path %></button>

<table>
  <thead>
    <tr>
      <th>Training Type</th>
      <th>Pet Name</th>
      <th>Appointment Date</th>
      <th>Appointment Time</th>
      <th>Length of Visit</th>
      <th>Client Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.appType %></td>
        <td><%= appointment.appClient %></td>
        <td><%= appointment.appDate %></td>
        <td><%= appointment.appTime %></td>
        <td><%= appointment.appLength %></td>
        <td><%= appointment.client_id %></td>
        <td><button class="tableButton"><%= link_to 'Show', appointment %></button></td>
        <td><button class="tableButton"><%= link_to 'Edit', edit_appointment_path(appointment) %></button></td>
        <td><button class="tableButton"><%= link_to 'Delete', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Training Type:</strong>
  <%= @appointment.appType %>
</p>

<p>
  <strong>Pet Name:</strong>
  <%= @appointment.appClient %>
</p>

<p>
  <strong>Appointment Date:</strong>
  <%= @appointment.appDate %>
</p>

<p>
  <strong>Appointment Time:</strong>
  <%= @appointment.appTime %>
</p>

<p>
  <strong>Length of Visit:</strong>
  <%= @appointment.appLength %>
</p>

<p>
  <strong>Client Name:</strong>
  <%= @appointment.client_id %>
</p>

<button class="tableButton"><%= link_to 'Edit', edit_appointment_path(@appointment) %></button>
<button class="tableButton"><%= link_to 'Back', appointments_path %></button>

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.phone %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book a Session - The Dog Lover</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
        <div class="linksToPages">
              <div class="homeShortcut">
                <div class="shortcut-text">
                  <p>
                    <a href="index.html">
                      <figure>
                      <img src="Pictures/homeicon.jpg" id="icon1">
                      <figcaption>Home</figcaption>
                      </figure>
                    </a>
                  </p>
                </div>
              </div>

            <div class="vlogShortcut">
              <div class="shortcut-text">
                <p>
                  <a href="vlog.html">
                    <figure>
                    <img src="Pictures/vlogicon.jpg" id="icon1">
                    <figcaption>Vlog</figcaption>
                    </figure>
                  </a>
                </p>
              </div>
            </div>
            
            <div class="aboutUsShortcut">
              <div class="shortcut-text">
                <p>
                  <a href="about_us.html">
                    <figure>
                    <img src="Pictures/abouticon.jpg" id="icon1">
                    <figcaption>About Us</figcaption>
                    </figure>
                  </a>
                </p>
              </div>
            </div>
          
        </div>

        <div class="title">
          Book a Session
        </div>
        
        
    </header>

  <body>
    <%= yield %>
  </body>
</html>